### ISSUE TITLE
Required module not found when module finishes in .android.js and .ios.js

### ISSUE THREAD

**Issue by maraujop** [guzart/eslint-import-resolver-reactnative#1]
Hi Arturo,

Currently, this resolver fails to resolve correctly when a module is suffixed by `.android.js` and `.ios.js`. It would be great if you could add support to this RN feature.

Thanks, cheers
Miguel

**Comment by guzart** [comment]
Hi Miguel, thanks for letting me know. However I couldn't replicate the problem, this is what I tried:

```javascript
// Component.android.js
export default {
  message: 'Android',
};
```

```javascript
// Component.ios.js
export default {
  message: 'iOS',
};
```

```javascript
// index.js
import Component from './Component';

console.log(Component);
```

Could your provide me with a better way to reproduce the error?

**Comment by guzart** [comment]
I guess you've solved your problem or moved on, if there's something else I can do to help don't hesitate to re-open the issue.
