### ISSUE TITLE
Unable to resolve path to module 'Dimensions' (import-no-unresolved)

### ISSUE THREAD

**Issue by bristoljon** [guzart/eslint-import-resolver-reactnative#2]
Fairly new to react native so feel free to point me in right direction if this is not the right place but I'm getting lint error at..

`import Dimensions from 'Dimensions'`

Is this something that this import resolver should be able to handle or do I need to add additional configuration?

Cheers

**Comment by guzart** [comment]
Hi, I believe you should be importing `Dimensions` from the `react-native` package

`import { Dimensions } from 'react-native'`

That is, unless you are using a different module resolution, or if it's different in the latest version of react-native. 

The above snippet works for me with v0.42.0. Let me know if this works for you

**Comment by bristoljon** [comment]
Ah, cheers for that. Not sure why we were importing it like that but above works as well and avoids the linting error. Maybe it was the old way of doing things, we are on 0.41.0
